package projectcreation1;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class add_customfields {
	@Test
	public void customm() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "C:\\Selenium\\chromedriver.exe");	 
		  ChromeDriver driver = new ChromeDriver();
		  driver.manage().window().maximize();
		  driver.get("https://niftyuat.com/");
		  driver.findElement(By.xpath("//input[@id='login-email']")).sendKeys("ankit.k+test000@gortnm.in");
		  Thread.sleep(4000);
		  driver.findElement(By.id("login-password")).sendKeys("12345678");
		  Thread.sleep(2000);
	  	  driver.findElement(By.className("section-foot")).click();
	  	  Thread.sleep(20000);
	  	  driver.findElement(By.xpath("//span[@class='btn visible-on-hover nav-btn-add']")).click();
	  	  Thread.sleep(5000);
	  	  driver.findElement(By.cssSelector("input[placeholder='Enter project name...']")).sendKeys("Task creation 1");
	  	  Thread.sleep(2000);
	  	  WebElement wb = driver.findElement(By.cssSelector("div[class='section-step step-1 active'] button[class='btn btn-success ']"));
	  	  wb.click(); // project creation
	  	  System.out.println("Project Created Successfully");
	  	  Thread.sleep(5000);
		  driver.findElement(By.xpath("//button[contains(text(),'Add a Task')]")).click();
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//div[@class='multi-line-input edit-panel-input empty']")).sendKeys("test1");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-small btn-success']")).click();
		  Thread.sleep(5000);
		  System.out.println("Task Created Successfully");
		  driver.findElement(By.xpath("//div[@class='task-overlay']")).click();
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[4]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Budget");
		  driver.findElement(By.xpath("//input[@placeholder='0']")).clear();
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//input[@placeholder='0']")).sendKeys("1000");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  driver.findElement(By.xpath("//div[@class='control-item-inner']")).click();
		  System.out.println("Start timer for budget custom field");
		  Thread.sleep(5000);
		  driver.findElement(By.xpath("(//div[@class='control-item-inner'])[3]")).click();
		  System.out.println("Stop timer");
		  System.out.print("Budget custom field created successfully");
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("text");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Text custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[6]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Dropdown");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//input[@placeholder='Option name']")).sendKeys("First");
		  driver.findElement(By.xpath("//span[@class='color-select-trigger']")).click();
		  driver.findElement(By.xpath("(//span[@class='color-block-click-overlay'])[3]")).click();
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Dropdown custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[7]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Number");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Number custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[8]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("URL");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("URL custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[9]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Phone");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Phone custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[10]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Email");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Email custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[11]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Location");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Location custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[12]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Currency");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Currency custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[13]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Checkbox");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Checkbox custom field created successfully");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[@class='btn btn-circle btn-xxsmall btn-simple btn-icon btn-colored']")).click();
		  driver.findElement(By.xpath("(//div[@class='item-inner'])[14]")).click();
		  driver.findElement(By.xpath("//input[@placeholder='Give it a name…']")).sendKeys("Date");
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//button[normalize-space()='Create field']")).click();
		  System.out.println("Date custom field created successfully");
		  Thread.sleep(2000);
	}
}
